mlp: !mlp
  lr: 0.01
  epochs: 100
  batch_size: 64
  hidden_dims: [256, 128, 64, 32, 16]
  dropout: 0.2

cnn1d: !cnn1d
  lr: 0.001
  epochs: 30
  batch_size: 64
  dropout: 0.2

lstm: !lstm
  lr: 0.001
  epochs: 50
  batch_size: 64
  hidden_dim: 32

gru: !gru
  lr: 0.001
  epochs: 20
  batch_size: 64
  hidden_dim: 32

bilstm: !bilstm
  lr: 0.001
  epochs: 50
  batch_size: 64
  hidden_dim: 32

gru: !bigru
  lr: 0.001
  epochs: 50
  batch_size: 64
  hidden_dim: 32

res_bilstm: !res_bilstm
  lr: 0.005
  epochs: 20
  batch_size: 64
  l2: 0.005
  hidden_dim: 32
  block_num: 2
